Feature/135/implement create for art
project-studying-dotnet/Streetcode-Server-June pull request #161
Opened 2024-06-23 21:18 UTC by kiyanovskaa

2024-06-23 22:35 UTC, metrondir commented on Streetcode/Streetcode.BLL/MediatR/Media/Art/Create/CreateArtHandler.cs
> +                const string errorMsg = "Cannot convert ArtCreateUpdateDTO to Art";
use error message from resource

2024-06-24 13:56 UTC, Shavronskyy requested changes
remove file program.cs or comment line 35

2024-06-24 13:58 UTC, Shavronskyy approved these changes
LGTM

2024-06-24 14:04 UTC, metrondir approved these changes
lgtm

2024-06-24 14:43 UTC, merged