[DRAFT] 182 login endpoint
project-studying-dotnet/Streetcode-Server-June pull request #223
Opened 2024-06-30 19:59 UTC by serhiiyasenev

dev
## JIRA

* [Main JIRA ticket 182](https://github.com/project-studying-dotnet/Streetcode-Server-June/issues/182)

2024-06-30 21:46 UTC, Shavronskyy requested changes
Write tests for handler

2024-07-01 06:45 UTC, vladtymo submitted a review, later dismissed
There's also a task for login handler on the board, but you have implemented the logic.
Discuss responsibilities with team members

2024-07-01 06:45 UTC, vladtymo commented on Streetcode/Streetcode.BLL/MediatR/Account/Login/LoginUserHandler.cs
> +        // already created User without password but token is generated
Why don't you validate user email and password before login?

2024-07-01 09:36 UTC, Shavronskyy requested changes

2024-07-01 09:42 UTC, serhiiyasenev commented on Streetcode/Streetcode.BLL/MediatR/Account/Login/LoginUserHandler.cs
> +        // already created User without password but token is generated
fixed

2024-07-01 09:44 UTC, serhiiyasenev commented on Streetcode/Streetcode.BLL/MediatR/Account/Login/LoginUserHandler.cs
> +        var accessToken = await _tokenService.GenerateAccessToken(user, claims);
done

2024-07-01 15:10 UTC, Shavronskyy requested changes

2024-07-01 15:10 UTC, Shavronskyy commented on Streetcode/Streetcode.BLL/DTO/Users/LoginResultDTO.cs
> +        public RefreshTokenDTO RefreshToken { get; set; }
use tokeResponseDTO

2024-07-01 15:12 UTC, serhiiyasenev commented on Streetcode/Streetcode.BLL/DTO/Users/LoginResultDTO.cs
> +        public RefreshTokenDTO RefreshToken { get; set; }
instead of LoginResultDTO? and why?

2024-07-01 15:13 UTC, metrondir commented on Streetcode/Streetcode.BLL/MediatR/Account/Login/LoginUserHandler.cs
> +
we decide to set tokens in cookies and return only user

2024-07-01 15:15 UTC, Shavronskyy commented on Streetcode/Streetcode.BLL/DTO/Users/LoginResultDTO.cs
> +        public RefreshTokenDTO RefreshToken { get; set; }
tokenResponseDTO have fields AccessToken and RefreshTokenDTO RefreshToken
you can use 1 tokenResponseDTO instead 2 fields(access and refresh tokens)

2024-07-01 18:33 UTC, serhiiyasenev commented on Streetcode/Streetcode.BLL/DTO/Users/LoginResultDTO.cs
> +        public RefreshTokenDTO RefreshToken { get; set; }
but it doesn't have `public UserDTO User { get; set; }` property

2024-07-01 19:06 UTC, serhiiyasenev commented on Streetcode/Streetcode.BLL/DTO/Users/LoginResultDTO.cs
> +        public RefreshTokenDTO RefreshToken { get; set; }
in any case now it doesn't matter because we use cookies and return UserDto

2024-07-01 19:06 UTC, serhiiyasenev commented on Streetcode/Streetcode.BLL/MediatR/Account/Login/LoginUserHandler.cs
> +
updated

2024-07-01 19:13 UTC, metrondir approved these changes
lgtm!

2024-07-01 21:38 UTC, kiyanovskaa approved these changes

2024-07-01 22:24 UTC, merged