Unit testing for GetAllTerms_Handler_Testing finished
project-studying-dotnet/Streetcode-Server-June pull request #25
Opened 2024-06-06 16:46 UTC by BohdanLytvynov

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2024-06-07 03:40 UTC, Forestieur approved these changes

2024-06-08 10:27 UTC, vladtymo reviewed
The code looks good! But follow the file/folder naming style you choose

2024-06-10 14:09 UTC, metrondir requested changes
Change structure of folders should be like that /MediatRTests/Streetcode/Term/GetAllTermsHandlerTests.cs

2024-06-10 16:32 UTC, metrondir approved these changes

2024-06-10 18:01 UTC, merged