fix flaky tests
project-studying-dotnet/Streetcode-Server-June pull request #274
Opened 2024-07-07 19:06 UTC by serhiiyasenev

## Describe your changes . Please include a summary of the changes and  also include relevant motivation and context

## Issue ticket (235)[https://github.com/project-studying-dotnet/Streetcode-Server-June/issues/235]

## Checklist before requesting a review
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Have you lint your code locally before submission?
- [ ] If that PR have tests
- [ ] I have performed a self-review of my code

2024-07-07 19:23 UTC, metrondir approved these changes
lgtm!

2024-07-08 04:53 UTC, Forestieur commented on Streetcode/Streetcode.BLL/Resources/MessageResourceContext.cs
> +                entityId = formatValue[0].ToString();
it shows error wrongfully, for example "Cannot find any Art with corresponding id: DeleteArtCommand { id = 1 }" instead of "Cannot find any Art with corresponding id: 1"

2024-07-08 06:06 UTC, serhiiyasenev commented on Streetcode/Streetcode.BLL/Resources/MessageResourceContext.cs
> +                entityId = formatValue[0].ToString();
yes, I want to show it in this way because it looks more informative

2024-07-08 06:10 UTC, Shavronskyy requested changes

2024-07-08 06:10 UTC, Shavronskyy commented on Streetcode/Streetcode.XUnitTest/MediatRTests/Streetcode/Facts/GetFactByStreetcodeIdHandlerTests.cs
> +            Assert.Equal(expectedErrorMessage, result.Errors.FirstOrDefault()?.Message);
use Assert multiple

2024-07-08 06:10 UTC, Shavronskyy commented on Streetcode/Streetcode.XUnitTest/MediatRTests/Streetcode/Facts/GetFactByStreetcodeIdHandlerTests.cs
> +            Assert.Equal(expectedErrorMessage, result.Errors.FirstOrDefault()?.Message);
in another tests too
we must to use assert multiple if we need to use a few Asserts

2024-07-08 08:47 UTC, serhiiyasenev commented on Streetcode/Streetcode.XUnitTest/MediatRTests/Streetcode/Facts/GetFactByStreetcodeIdHandlerTests.cs
> +            Assert.Equal(expectedErrorMessage, result.Errors.FirstOrDefault()?.Message);
fixed

2024-07-08 08:56 UTC, Shavronskyy approved these changes
Lgtm

2024-07-08 09:29 UTC, merged